reset;

option solver cplex;

model sudokuSolver.mod;
data sudokuEasy.dat;

solve;
#display the results
for {i in N}{
   for {j in N}{
      for {k in N}{
         if (z[i,j,k] == 1) then printf "%3i", k;
      };
      if ((j mod m) == 0) then printf " | ";
   };
   printf "\n";
   if ((i mod m) == 0) then {
      for {j in 1..m}{
         for {k in 1..m-1}{ printf "---" };
         if (j < m) then
            printf "----+-";
         else
            printf "----+\n";
      };
   };
};